### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by sobradob** [vanatteveldt/learningr#3]
Cool project! I presume you meant `corpustools`and not `corputools`.

**Comment by SherylHohman** [comment]
where ?

**Comment by vanatteveldt** [comment]
https://github.com/vanatteveldt/learningr/commit/fd16c8740841afdd5086fd5f2c328f18613841f4

Is that the one you meant? If not, can you give the file containing the typo?

**Comment by sobradob** [comment]
Yes that was it. Sorry for not specifying the file.
